---
- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Create user informatica
  user:
    name: "{{ informatica_user }}"
    password: "{{ informatica_passwd | password_hash('sha512') }}"
    groups: wheel
    append: yes
    state: present
    createhome: yes

# Add both soft and hard limit for the user "{{ informatica_user }}".
- pam_limits:
    domain: "{{ informatica_user }}"
    limit_type: '-'
    limit_item: nofile
    value: 65537
    
# Reload settings from all system configuration files
- name: reload settings from all system configuration files
  shell: sysctl --system
