---

- name: Set PostgreSQL dotless version fact
  set_fact:
    __postgresql_version_dotless: "{{ postgresql_version | replace('.', '') }}"
    __postgresql_command_sep: "{{ postgresql_version is version('10', '>=') | ternary('-', '') }}"

- name: Copy rpm
  copy:
    src: rpm10
    dest: /tmp10
    owner: user
    group: user
    mode: '0644'

- name: Installed the rpm files
  shell: yum localinstall *.rpm -y
  args:
    chdir: /tmp/rpm10

- name: Check for pgdata directory
  stat:
    path: "{{ postgresql_pgdata }}/PG_VERSION"
  register: pgdata_stat

- name: Initialize database (RedHat >= 7)
  command: >-
    /usr/pgsql-{{ postgresql_version }}/bin/postgresql{{ __postgresql_command_sep }}{{
      __postgresql_version_dotless }}-setup initdb
  when: not pgdata_stat.stat.exists
